version: 0.2

phases:
  pre_build:
    commands:
      - npm i node-gyp
      - npm install --force
      - npm update
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: ./
